[project]
name = "gym-train"
version = "0.1.0"
description = "Этот бот помогает записывать тренировки в зале и дома"
authors = [
    {name = "nevek12",email = "vladnevvk@mail.ru"}
]
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "aiogram (>=3.17.0,<4.0.0)",
    "environs (>=14.1.0,<15.0.0)",
    "asyncpg (>=0.30.0,<0.31.0)",
]


[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"
